In [99]:
import numpy as np

In [100]:
a = ["epoch", "accuracy", "precision"]

accuracy = [3, 4]
precision = [5, 2]
metrics = np.array([accuracy, precision])

In [101]:
metrics

array([[3, 4],
       [5, 2]])

In [102]:
epochs = np.arange(1, len(metrics[0]) + 1)
epochs

array([1, 2])

In [103]:
hist = np.concatenate(([epochs], metrics), axis=0)
hist

array([[1, 2],
       [3, 4],
       [5, 2]])

In [104]:
metrics

array([[3, 4],
       [5, 2]])

In [105]:
metrics.T

array([[3, 5],
       [4, 2]])

In [106]:
hist = np.concatenate(([a], metrics.T), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
hist

array([['epoch', 'accuracy', 'precision'],
       ['1', '3', '5'],
       ['2', '4', '2']], dtype='<U21')

In [ ]:
for a in hist:
    print(a)

['epoch' 'accuracy' 'precision']
['1' '3' '5']
['2' '4' '2']
