In [74]:

import pandas as pd
import torch

import matplotlib.pyplot as plt
import seaborn as sns

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [75]:
input = torch.tensor([[ 0.0495, -2.0465, -1.2053],
        [ 1.9395, -1.9850,  0.3126]])
input

tensor([[ 0.0495, -2.0465, -1.2053],
        [ 1.9395, -1.9850,  0.3126]])

In [84]:
i, v = torch.max(input, dim=1)
print(i)
print(v)

tensor([0.0495, 1.9395])
tensor([0, 0])


In [76]:
torch.softmax(input, dim=0)

tensor([[0.1312, 0.4846, 0.1798],
        [0.8688, 0.5154, 0.8202]])

In [77]:
torch.softmax(input, dim=1)

tensor([[0.7102, 0.0873, 0.2025],
        [0.8222, 0.0162, 0.1616]])

In [81]:
input2 = torch.tensor([[ 0.0495, -2.0465, -1.2053]])
input2

tensor([[ 0.0495, -2.0465, -1.2053]])

In [83]:
i, v = torch.max(input2, dim=1)
print(i)
print(v)

tensor([0.0495])
tensor([0])


In [ ]:
torch.softmax(input2, dim=0)

tensor([0.7102, 0.0873, 0.2025])

In [ ]:
torch.softmax(input2, dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [ ]:
tensor_a = torch.tensor([[-0.1262,  0.0347,  0.1791,  0.0516, -0.0399,  0.0688, -0.0189, -0.0438,
         -0.0325,  0.0863, -0.1631,  0.0380, -0.0172, -0.0384,  0.0938, -0.1610,
          0.0565, -0.0790,  0.0154, -0.1305, -0.1034, -0.0886,  0.0012,  0.0973,
         -0.0160,  0.0524,  0.0039, -0.1297, -0.0176,  0.2532, -0.0861,  0.3075,
         -0.0585, -0.0149,  0.0502, -0.1132,  0.5472, -0.1486, -0.0775,  0.0902,
         -0.0993, -0.0560, -0.0079,  0.2336,  0.1235, -0.0204, -0.0683, -0.0195,
         -0.0181, -0.0026,  0.0233, -0.0535,  0.1506, -0.0182, -0.0643, -0.0511,
         -0.0186,  0.0850, -0.0225, -0.2193,  0.0462,  0.1263, -0.1379, -0.1927,
         -0.0179],
        [-0.0500,  0.0379,  0.1173,  0.0272, -0.0229,  0.0173, -0.0210, -0.0035,
          0.0143, -0.0560, -0.0893,  0.0090, -0.0595, -0.1233,  0.0609, -0.0936,
         -0.0010, -0.0210,  0.0313, -0.0816, -0.1358, -0.0380, -0.0101,  0.0209,
          0.0422,  0.0473, -0.1277, -0.1114,  0.0372,  0.1322, -0.0009,  0.2534,
          0.0493,  0.1617, -0.0116, -0.0530,  0.3419, -0.1002, -0.0961,  0.0967,
         -0.1823, -0.0196, -0.0310,  0.1992,  0.1999, -0.0772,  0.0492,  0.0414,
         -0.1233,  0.0529, -0.0640, -0.0633,  0.1512,  0.0245, -0.0416, -0.0864,
          0.0036,  0.0891,  0.0134, -0.0973,  0.0475,  0.0792, -0.0393, -0.1007,
         -0.0148]])

tensor_b = torch.tensor([[0.0134, 0.0158, 0.0182, 0.0161, 0.0147, 0.0163, 0.0150, 0.0146, 0.0148,
         0.0166, 0.0130, 0.0158, 0.0150, 0.0147, 0.0168, 0.0130, 0.0161, 0.0141,
         0.0155, 0.0134, 0.0138, 0.0140, 0.0153, 0.0168, 0.0150, 0.0161, 0.0153,
         0.0134, 0.0150, 0.0197, 0.0140, 0.0207, 0.0144, 0.0150, 0.0160, 0.0136,
         0.0264, 0.0131, 0.0141, 0.0167, 0.0138, 0.0144, 0.0151, 0.0193, 0.0173,
         0.0149, 0.0142, 0.0150, 0.0150, 0.0152, 0.0156, 0.0145, 0.0177, 0.0150,
         0.0143, 0.0145, 0.0150, 0.0166, 0.0149, 0.0123, 0.0160, 0.0173, 0.0133,
         0.0126, 0.0150],
        [0.0145, 0.0159, 0.0172, 0.0157, 0.0149, 0.0155, 0.0149, 0.0152, 0.0155,
         0.0144, 0.0140, 0.0154, 0.0144, 0.0135, 0.0162, 0.0139, 0.0152, 0.0149,
         0.0157, 0.0141, 0.0133, 0.0147, 0.0151, 0.0156, 0.0159, 0.0160, 0.0134,
         0.0137, 0.0158, 0.0174, 0.0153, 0.0197, 0.0160, 0.0179, 0.0151, 0.0145,
         0.0215, 0.0138, 0.0139, 0.0168, 0.0127, 0.0150, 0.0148, 0.0186, 0.0186,
         0.0141, 0.0160, 0.0159, 0.0135, 0.0161, 0.0143, 0.0143, 0.0178, 0.0156,
         0.0146, 0.0140, 0.0153, 0.0167, 0.0155, 0.0138, 0.0160, 0.0165, 0.0147,
         0.0138, 0.0150]])

tensor = torch.stack((tensor_a, tensor_b), dim=0)
tensor

tensor([[[-0.1262,  0.0347,  0.1791,  0.0516, -0.0399,  0.0688, -0.0189,
          -0.0438, -0.0325,  0.0863, -0.1631,  0.0380, -0.0172, -0.0384,
           0.0938, -0.1610,  0.0565, -0.0790,  0.0154, -0.1305, -0.1034,
          -0.0886,  0.0012,  0.0973, -0.0160,  0.0524,  0.0039, -0.1297,
          -0.0176,  0.2532, -0.0861,  0.3075, -0.0585, -0.0149,  0.0502,
          -0.1132,  0.5472, -0.1486, -0.0775,  0.0902, -0.0993, -0.0560,
          -0.0079,  0.2336,  0.1235, -0.0204, -0.0683, -0.0195, -0.0181,
          -0.0026,  0.0233, -0.0535,  0.1506, -0.0182, -0.0643, -0.0511,
          -0.0186,  0.0850, -0.0225, -0.2193,  0.0462,  0.1263, -0.1379,
          -0.1927, -0.0179],
         [-0.0500,  0.0379,  0.1173,  0.0272, -0.0229,  0.0173, -0.0210,
          -0.0035,  0.0143, -0.0560, -0.0893,  0.0090, -0.0595, -0.1233,
           0.0609, -0.0936, -0.0010, -0.0210,  0.0313, -0.0816, -0.1358,
          -0.0380, -0.0101,  0.0209,  0.0422,  0.0473, -0.1277, -0.1114,
           0.0372,  0.

In [ ]:
tensor_a.shape

torch.Size([2, 65])

In [ ]:
tensor.shape

torch.Size([2, 2, 65])

In [ ]:
torch.softmax(tensor_a, dim=0)

tensor([[0.4810, 0.4992, 0.5154, 0.5061, 0.4958, 0.5129, 0.5005, 0.4899, 0.4883,
         0.5355, 0.4816, 0.5072, 0.5106, 0.5212, 0.5082, 0.4832, 0.5144, 0.4855,
         0.4960, 0.4878, 0.5081, 0.4874, 0.5028, 0.5191, 0.4855, 0.5013, 0.5329,
         0.4954, 0.4863, 0.5302, 0.4787, 0.5135, 0.4731, 0.4560, 0.5154, 0.4850,
         0.5511, 0.4879, 0.5046, 0.4984, 0.5207, 0.4909, 0.5058, 0.5086, 0.4809,
         0.5142, 0.4707, 0.4848, 0.5263, 0.4861, 0.5218, 0.5024, 0.4999, 0.4893,
         0.4943, 0.5088, 0.4945, 0.4990, 0.4910, 0.4695, 0.4997, 0.5118, 0.4754,
         0.4770, 0.4992],
        [0.5190, 0.5008, 0.4846, 0.4939, 0.5042, 0.4871, 0.4995, 0.5101, 0.5117,
         0.4645, 0.5184, 0.4928, 0.4894, 0.4788, 0.4918, 0.5168, 0.4856, 0.5145,
         0.5040, 0.5122, 0.4919, 0.5126, 0.4972, 0.4809, 0.5145, 0.4987, 0.4671,
         0.5046, 0.5137, 0.4698, 0.5213, 0.4865, 0.5269, 0.5440, 0.4846, 0.5150,
         0.4489, 0.5121, 0.4954, 0.5016, 0.4793, 0.5091, 0.4942, 0.4914, 0.5191,
  

In [ ]:
torch.softmax(tensor, dim=0)

tensor([[[0.4652, 0.5047, 0.5401, 0.5089, 0.4864, 0.5131, 0.4915, 0.4854,
          0.4882, 0.5174, 0.4561, 0.5055, 0.4920, 0.4867, 0.5192, 0.4566,
          0.5101, 0.4767, 0.5000, 0.4641, 0.4707, 0.4744, 0.4965, 0.5201,
          0.4923, 0.5091, 0.4972, 0.4643, 0.4919, 0.5581, 0.4750, 0.5712,
          0.4818, 0.4925, 0.5085, 0.4683, 0.6273, 0.4597, 0.4771, 0.5184,
          0.4718, 0.4824, 0.4943, 0.5534, 0.5265, 0.4912, 0.4794, 0.4914,
          0.4917, 0.4956, 0.5019, 0.4830, 0.5332, 0.4917, 0.4804, 0.4836,
          0.4916, 0.5171, 0.4907, 0.4424, 0.5075, 0.5272, 0.4623, 0.4489,
          0.4918],
         [0.4839, 0.5055, 0.5250, 0.5029, 0.4906, 0.5005, 0.4910, 0.4953,
          0.4997, 0.4824, 0.4742, 0.4984, 0.4815, 0.4659, 0.5112, 0.4732,
          0.4960, 0.4910, 0.5039, 0.4761, 0.4628, 0.4868, 0.4937, 0.5013,
          0.5066, 0.5078, 0.4648, 0.4688, 0.5053, 0.5287, 0.4960, 0.5582,
          0.5083, 0.5359, 0.4933, 0.4831, 0.5794, 0.4715, 0.4725, 0.5200,
          0.4514, 0